# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.network "forwarded_port", guest: 80, host: 1080
  config.vm.synced_folder "../", "/var/www/varena2",
      owner: "www-data", group: "www-data",
      type: "rsync"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "jessie", autostart: true do |myhost|
      myhost.vm.box = "debian/jessie64"
      myhost.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
  end

end
